name: Test CICD Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Stage 1: Build
    runs-on: ubuntu-latest
    name: Build Java Project

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-jar
          path: target/github-cicd-test.jar

  docker-build:
    # Stage 2: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Built Artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-jar

      - name: Verify Downloaded Artifact
        run: |
          echo "Listing contents of the current directory:"
          ls -l
          echo "Listing contents of the target directory:"
          ls -l target

      - name: Create Target Directory
        run: |
          mkdir -p target
          cp github-cicd-test.jar target/ # Ensure the JAR is in the target directory

      - name: Build Docker image
        run: |
          docker build -t adityaramachandran/github-cicd-test .

  trivy-scan:
    # Stage 3: Run Trivy Scan
    runs-on: ubuntu-latest
    needs: docker-build
    name: Run Trivy Scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Built Jar Artifact
        uses: actions/download-artifact@v3
        with:
          name: built-jar

      - name: Run Trivy Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: 'trivy.yaml'

  docker-publish:
    # Stage 4: Publish Docker Image
    if: success() || failure() && github.ref == 'refs/heads/master' # Only run if on the master branch
    runs-on: ubuntu-latest
    name: Publish Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: adityaramachandran/github-cicd-test
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
